[package]
name = "rust_tools"
version = "0.1.0"
edition = "2021"
description = "Devlopment Tools By Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.5", features = ["derive"] }
md5 = "0.7.0"
sha = "1.0.3"